version: '3.8'

services:
  php:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  mysql:
    image: mariadb:10.11.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
